name: Host

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: setup git config
        run: |
          git config user.name "pantsufan"
          git config user.email "joel28@protonmail.com"
          
      - name: commit
        run: |
          # Stage the file, commit and push
          git rm hosts
          git commit -m "Removed Host"
          git push origin main

      - name: Start Building
        run:  |
          echo "Starting....."
          wget https://raw.githubusercontent.com/pantsufan/Project-Lite/main/hosts
          wget https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/hosts.txt
          cat hosts.txt >> hosts
          rm hosts.txt
          echo "Done Building!"
        
      - name: commit
        run: |
          # Stage the file, commit and push
          git add hosts
          git commit -m "Host File Updated"
          git push origin main
