name: Build Hosts File
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  build-hosts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: setup git config
      run: |
        git config user.name "pantsufan"
        git config user.email "joel28@protonmail.com"

    - name: Remove old file
      run: |
          git rm hosts
          git commit -m "Removed Host File"
          git push origin main
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y php-cli curl

    - name: Download converter.php
      run: |
        curl -o converter.php https://gist.githubusercontent.com/pantsufan/e4b8876154d1436d8b13743bb07f3a8a/raw/converter.php

    - name: Run Script
      run: |
        echo "Project Lite"
        curl -O https://adaway.org/hosts.txt
        sed "1,24d" hosts.txt >> adaway
        rm hosts.txt
        sed -i -e "s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/0.0.0.0/g" adaway
        sed -i "/^$/d" adaway
        sed -i "/^#/d" adaway
        php converter.php
        sed -i "1,6d" AdguardMobileAds.txt
        sed -i "1,6d" AdguardMobileSpyware.txt
        cat AdguardMobileSpyware.txt >> AdguardMobileAds.txt
        rm AdguardMobileSpyware.txt
        mv AdguardMobileAds.txt adguard
        curl -O https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt
        sed -i "1,15d" d3host.txt
        sed -i "/^$/d" d3host.txt
        sed -i "/^#/d" d3host.txt
        cat d3host.txt >> adguard
        rm d3host.txt
        cat adguard >> adaway
        sort -u adaway > hosts
        rm adaway
        rm adguard
        wget https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/hosts.txt
        cat hosts.txt >> hosts
        rm hosts.txt
        sort -u hosts > hosts_filter
        {
          echo "# PROJECT LITE"
          echo "# Generated by Kninja"
          echo "# Blocked domains: $(cat hosts_filter | wc -l)"
          echo "# Date: $(date)"
          echo ""
          echo "# BEGIN HEADER"
          echo "127.0.0.1       localhost"
          echo "255.255.255.255 broadcasthost"
          echo "::1             localhost"
          echo "::1             ip6-localhost ip6-loopback"
          echo "fe00::0         ip6-localnet"
          echo "ff00::0         ip6-mcastprefix"
          echo "ff02::1         ip6-allnodes"
          echo "ff02::2         ip6-allrouters"
          echo "ff02::3         ip6-allhosts"
          echo "# END HEADER"
          echo ""
          echo "# BEGIN BLOCKLIST"
          cat hosts_filter
        } > hosts_new
        rm hosts
        mv hosts_new hosts
        rm hosts_filter
        echo "Done Building!"

    - name: Commit and Push Changes
      run: |
        git add hosts
        git commit -m "Update hosts file"
        git push origin main
