name: Host

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Start Building
        run: |
          echo "Satrting...."
          wget =https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
          wget https://o0.pages.dev/Lite/hosts.txt
          sed '1,33d' hosts.txt >> hosts
          rm hosts.txt
          wget https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/hosts.txt
          cat hosts.txt >> hosts
          mv hosts og_hosts
          wget https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
          mv hosts hosts.txt
          sed '1,12d' hosts.txt >> hosts
          cat hosts >> og_hosts
          mv og_hosts hosts
          rm hosts.txt
          echo "Done Building!"

      - name: setup git config
        run: |
          git config user.name "pantsufan"
          git config user.email "joel28@protonmail.com"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add hosts
          git commit -m "Host File Updated"
          git push origin main
