name: Build Hosts File
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-hosts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: setup git config
      run: |
        git config user.name "OodavidsinoO"
        git config user.email "david.sin@tuta.io"

    - name: Remove old file
      run: |
          git rm hosts
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y php-cli curl

    - name: Download converter.php
      run: |
        curl -o converter.php https://raw.githubusercontent.com/OodavidsinoO/BlockAdsNext/refs/heads/main/converter.php

    - name: Run Script
      run: |
        echo "Project Lite"
        php converter.php
        # ==========================
        # Remove first 5 lines for all .txt files
        sed -i "1,5d" *.txt
        # ==========================
        # Combine all .txt
        cat *.txt > hosts.tmp
        rm *.txt
        # ==========================
        # Remove duplicates
        awk '!seen[$0]++' hosts.tmp > hosts_filter
        {
          echo "# PROJECT BLOCKADSNEXT"
          echo "# Generated by OodavidsinoO"
          echo "# Blocked domains: $(cat hosts_filter | wc -l)"
          echo "# Date: $(date)"
          echo ""
          echo "# BEGIN HEADER"
          echo "127.0.0.1       localhost"
          echo "255.255.255.255 broadcasthost"
          echo "::1             localhost"
          echo "::1             ip6-localhost ip6-loopback"
          echo "fe00::0         ip6-localnet"
          echo "ff00::0         ip6-mcastprefix"
          echo "ff02::1         ip6-allnodes"
          echo "ff02::2         ip6-allrouters"
          echo "ff02::3         ip6-allhosts"
          echo "# END HEADER"
          echo ""
          echo "# BEGIN BLOCKLIST"
          cat hosts_filter
        } > hosts_new
        rm hosts.tmp
        mv hosts_new hosts
        rm hosts_filter
        echo "Done Building!"
        # ==========================
        # Update blockadsnext-update.json file
        # Get latest version of BlockAdsNext
        fileVersion=$(curl -s "https://api.github.com/repos/OodavidsinoO/BlockAdsNext/tags" | jq -r '.[0].name')
        # Change version number
        currentVersion=$fileVersion
        # Extract the major and minor version components
        major=$(echo "$currentVersion" | awk -F'.' '{print substr($1,2)}')
        minor=$(echo "$currentVersion" | awk -F'.' '{print $2}')
        # Increment the minor version, and reset to 0 if it reaches 99
        minor=$((minor + 1))
        if [ "$minor" -eq 100 ]; then
          minor=0
          major=$((major + 1))
        fi
        # Format the new version
        newVersion="v${major}.${minor}"
        fileName="BlockAdsNext-$newVersion.zip"
        dateStamp=$(date +"%Y%m%d")
        > blockadsnext-update.json
        echo "{
          \"version\": \"$newVersion\",
          \"versionCode\": \"$dateStamp\",
          \"zipUrl\": \"https://github.com/OodavidsinoO/BlockAdsNext/releases/download/$newVersion/$fileName\",
          \"changelog\": \"https://raw.githubusercontent.com/OodavidsinoO/BlockAdsNext/refs/heads/main/CHANGELOG.md\"
        }" > blockadsnext-update.json
        # ==========================
        # Generate changelog using git
         > CHANGELOG.md
        git log --oneline --decorate --graph -n 50 >> CHANGELOG.md

    - name: Commit and Push Changes
      run: |
        git add hosts blockadsnext-update.json CHANGELOG.md
        git commit -m "Update hosts file"
        git push origin main