name: Host

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Start Building
        run: |
          wget https://hosts.oisd.nl/
          mv index.html hosts
          wget https://o0.pages.dev/Lite/hosts.txt
          sed '1,33d' hosts.txt >> hosts
          wget https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/hosts.txt
          cat hosts.txt >> hosts
          mv hosts og_hosts
          wget https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
          mv hosts hosts.txt
          sed '1,12d' hosts.txt >> hosts
          cat hosts >> og_hosts
          mv og_hosts hosts
          rm hosts.txt
          wget https://gist.githubusercontent.com/pantsufan/ba4762d25de269dcdaa9f692ea6f9f5c/raw/9882032fa57fe910260d00fa959a80e0b05c2300/ms_adblock.txt
          cat ms_adblock.txt >> hosts
          rm ms_adblock.txt

      - name: setup git config
        run: |
          git config user.name "pantsufan"
          git config user.email "joel28@protonmail.com"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add hosts
          git commit -m "Host File Updated"
          git push origin main
